### ISSUE TITLE
implementation of auth without encryption 

### ISSUE THREAD

**Issue by mrturkmen06** [aau-network-security/haaukins-store#6]
I think, it could be nice to have authentication without encryption, which means without HTTPS and with auth. I think,  it should be possible, if not we can checkout how we can accomplish to run haaukins-store on local with auth and without encryption.

**Comment by gianmarcomennecozzi** [comment]
There is nothing to change in this repo about the communication without HTTPS. The problem was in haaukins and i have solved it in this commit https://github.com/aau-network-security/haaukins/commit/d465016dda76bc56debeccf5de3e75c0391f638d . 
In order to run haaukins and the store without TLS just change the `config.yml` file and the `.env` file respectively disabling the TLS.
